# Generated by Django 4.2.1 on 2023-06-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_myuser_first_name_myuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='mobile_number',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
