# Generated by Django 4.2.1 on 2023-06-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_myuser_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='otp',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
