# Generated by Django 4.2.1 on 2023-06-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_myuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='otp_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='otp_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_types',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Driver'), (3, 'Restaurant')], default=1),
        ),
    ]
